x-airflow-common:
  &airflow-common
  build:
    context: .
    dockerfile: airflow.Dockerfile
  env_file:
    - .env
  environment:
    &airflow-common-env
    AIRFLOW__CORE__EXECUTOR: CeleryExecutor
    AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://${POSTGRES_DB_USER}:${POSTGRES_DB_PASSWORD}@postgres:5432/${AIRFLOW_DB_NAME}
    AIRFLOW__CORE__AUTH_MANAGER: airflow.providers.fab.auth_manager.fab_auth_manager.FabAuthManager
    AIRFLOW__CELERY__RESULT_BACKEND: db+postgresql://${POSTGRES_DB_USER}:${POSTGRES_DB_PASSWORD}@postgres/${AIRFLOW_DB_NAME}
    AIRFLOW__CELERY__BROKER_URL: redis://:@redis:6379/0
    AIRFLOW__CORE__FERNET_KEY: ${AIRFLOW_FERNET_KEY}
    # AIRFLOW__CORE__SECRET_KEY: ${AIRFLOW_SECRET_KEY}
    AIRFLOW__CORE__DAGS_ARE_PAUSED_AT_CREATION: 'true'
    AIRFLOW__CORE__LOAD_EXAMPLES: 'false'
    # AIRFLOW__CORE__EXECUTION_API_SERVER_URL: 'http://airflow-apiserver:8080/execution/'
    AIRFLOW__SCHEDULER__ENABLE_HEALTH_CHECK: 'true'
    _PIP_ADDITIONAL_REQUIREMENTS: ${_PIP_ADDITIONAL_REQUIREMENTS:-}
    AIRFLOW__CORE__INTERNAL_API_URL: http://airflow-apiserver:8080
    AIRFLOW__API__AUTH_BACKENDS: airflow.api.auth.backend.basic_auth
  
    # AIRFLOW__CORE__INTERNAL_API_SECRET_KEY: ${AIRFLOW_SECRET_KEY}
    AIRFLOW__API__SECRET_KEY: ${AIRFLOW_SECRET_KEY}
    AIRFLOW__WEBSERVER__SECRET_KEY: ${AIRFLOW_SECRET_KEY}
    AIRFLOW__CORE__EXECUTION_API_SERVER_URL: 'http://airflow-apiserver:8080/execution/'

    AIRFLOW__API_AUTH__JWT_SECRET: "${AIRFLOW_SECRET_KEY}"
    DBT_HOST: postgres
  volumes:
    - .:/app
    - ./airflow/dags:/opt/airflow/dags
    - ./airflow/logs:/opt/airflow/logs
    - ./airflow/plugins:/opt/airflow/plugins
    - ./dbt_flights:/app/dbt_flights
    - shared-jars:/shared/jars:ro
    - spark-warehouse:/app/spark-warehouse
    - ${HOME}/.dbt:/home/airflow/.dbt
  user: "1000:0"
  depends_on:
    &airflow-common-depends-on
    redis:
      condition: service_healthy
    postgres:
      condition: service_healthy
    init-jars:
      condition: service_completed_successfully
  networks:
    - default
    - spark-network



services:
  init-jars:
    build:
      context: .
      dockerfile: spark.Dockerfile
    user: "root"
    container_name: ${PROJECT_NAME}-init-jars
    command: >
      bash -c "
        cp /opt/bitnami/spark/jars/delta-spark_2.12-3.2.0.jar /shared/jars/ &&
        cp /opt/bitnami/spark/jars/delta-storage-3.2.0.jar /shared/jars/ &&
        cp /opt/bitnami/spark/jars/postgresql-42.7.3.jar /shared/jars/ &&
        echo 'Jars copied successfully'
      "
    volumes:
      - shared-jars:/shared/jars


  hive-metastore:
    image: apache/hive:4.0.0
    container_name: ${PROJECT_NAME}-hive-metastore
    restart: unless-stopped
    depends_on:
      - init-jars
      - create-dbs
    environment:
      - SERVICE_NAME=metastore
      - DB_DRIVER=postgres
      - SERVICE_OPTS=-Djavax.jdo.option.ConnectionDriverName=org.postgresql.Driver -Djavax.jdo.option.ConnectionURL=jdbc:postgresql://postgres:5432/${SPARK_METASTORE_DB_NAME} -Djavax.jdo.option.ConnectionUserName=${POSTGRES_DB_USER} -Djavax.jdo.option.ConnectionPassword=${POSTGRES_DB_PASSWORD}
      - HIVE_AUX_JARS_PATH=/shared/jars/postgresql-42.7.3.jar
    command: >
      bash -c "
        if ! /opt/hive/bin/schematool -dbType postgres -info 2>/dev/null; then
          /opt/hive/bin/schematool -dbType postgres -initSchema
        fi &&
        /opt/hive/bin/hive --service metastore
      "
    volumes:
      - shared-jars:/shared/jars:ro
      - spark-warehouse:/app/spark-warehouse
    ports:
      - "9083:9083"
    networks:
      - default
      - spark-network

  # ---------------------------------------------------------
  # Spark Master
  # ---------------------------------------------------------
  spark-master:
    build:
      context: .
      dockerfile: spark.Dockerfile
    user: "root"
    container_name: ${PROJECT_NAME}-spark-master
    restart: unless-stopped
    environment:
      - SPARK_MODE=master
      - SPARK_MASTER_HOST=spark-master
      - SPARK_DRIVER_MEMORY=${SPARK_DRIVER_MEMORY:-2g}
      - SPARK_USER=root

      # Python
      - PYTHONPATH=/app
      - PYSPARK_PYTHON=/opt/bitnami/python/bin/python3
      - PYSPARK_DRIVER_PYTHON=/opt/bitnami/python/bin/python3

      # Delta Lake (JARs already baked into image)
      - SPARK_SQL_EXTENSIONS=io.delta.sql.DeltaSparkSessionExtension
      - SPARK_SQL_CATALOG_SPARK_CATALOG=org.apache.spark.sql.delta.catalog.DeltaCatalog

    volumes:
      - .:/app
      - ./conf/log4j2.properties:/opt/bitnami/spark/conf/log4j2.properties
      - spark-warehouse:/app/spark-warehouse
    ports:
      - "8080:8080"   # Spark Master UI
      - "7077:7077"   # Master RPC Port
      - "4040:4040"   # Application UI
    networks:
      - default
      - spark-network

  # ---------------------------------------------------------
  # Spark Worker
  # ---------------------------------------------------------
  spark-worker:
    build:
      context: .
      dockerfile: spark.Dockerfile
    user: "root"
    container_name: ${PROJECT_NAME}-spark-worker-1
    restart: unless-stopped
    depends_on:
      - spark-master

    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark-master:7077
      - SPARK_WORKER_CORES=${SPARK_WORKER_CORES:-1}
      - SPARK_WORKER_MEMORY=${SPARK_WORKER_MEMORY:-2g}
      - SPARK_USER=root

      # Python
      - PYTHONPATH=/app
      - PYSPARK_PYTHON=/opt/bitnami/python/bin/python3
      - PYSPARK_DRIVER_PYTHON=/opt/bitnami/python/bin/python3

      # Delta (already in image)
      - SPARK_SQL_EXTENSIONS=io.delta.sql.DeltaSparkSessionExtension
      - SPARK_SQL_CATALOG_SPARK_CATALOG=org.apache.spark.sql.delta.catalog.DeltaCatalog

    volumes:
      - .:/app
      - ./conf/log4j2.properties:/opt/bitnami/spark/conf/log4j2.properties
      - spark-warehouse:/app/spark-warehouse
    networks:
      - default
      - spark-network


  # spark-master:
  #   build:
  #     context: .
  #     dockerfile: spark.Dockerfile
  #   user: "root"
  #   container_name: ${PROJECT_NAME}-spark-master
  #   restart: unless-stopped
  #   depends_on:
  #   - hive-metastore
  #   environment:
  #     - SPARK_MODE=master
  #     - SPARK_DRIVER_MEMORY=${SPARK_DRIVER_MEMORY}
  #     - SPARK_USER=root
  #     - PYTHONPATH=/app
  #     - PYSPARK_PYTHON=/opt/bitnami/python/bin/python3
  #     - PYSPARK_DRIVER_PYTHON=/opt/bitnami/python/bin/python3
  #     - SPARK_JARS_PACKAGES=io.delta:delta-spark_2.12:3.2.0,org.postgresql:postgresql:42.7.3
  #     - SPARK_SQL_EXTENSIONS=io.delta.sql.DeltaSparkSessionExtension
  #     - SPARK_SQL_CATALOG=spark_catalog
  #     - SPARK_SQL_CATALOG_SPARK_CATALOG=org.apache.spark.sql.delta.catalog.DeltaCatalog
  #     - SPARK_HIVE_METASTORE_URIS=thrift://hive-metastore:9083
  #   # command: >
  #   #   /opt/bitnami/spark/bin/spark-class org.apache.spark.deploy.master.Master      
  #   volumes:
  #     - .:/app
  #     - ./conf/log4j2.properties:/opt/bitnami/spark/conf/log4j2.properties
  #     - shared-jars:/shared/jars 
  #   ports:
  #     - "8080:8080" # Spark Master UI
  #     - "4040:4040" # Spark Application UI
  #     - "7077:7077" # Spark Master Port
  #   # networks:
  #   #   - spark-network

  # spark-worker:
  #   build:
  #     context: .
  #     dockerfile: spark.Dockerfile
  #   user: "root"
  #   container_name: ${PROJECT_NAME}-spark-worker-1
  #   restart: unless-stopped
  #   # The worker depends on the master being available.
  #   depends_on:
  #     - spark-master

  #   # command: >
  #   #   /opt/bitnami/spark/bin/spark-class org.apache.spark.deploy.worker.Worker spark://spark-master:7077
        
  #   environment:
  #     - SPARK_MODE=worker
  #     - SPARK_MASTER_URL=spark://spark-master:7077 
  #     - SPARK_WORKER_CORES=${SPARK_WORKER_CORES:-1}
  #     - SPARK_WORKER_MEMORY=${SPARK_WORKER_MEMORY:-2g}
  #     - SPARK_USER=root
  #     - PYTHONPATH=/app
  #     - PYSPARK_PYTHON=/opt/bitnami/python/bin/python3
  #     - PYSPARK_DRIVER_PYTHON=/opt/bitnami/python/bin/python3
  #     - SPARK_JARS_PACKAGES=io.delta:delta-spark_2.12:3.2.0,org.postgresql:postgresql:42.7.3
  #     - SPARK_SQL_EXTENSIONS=io.delta.sql.DeltaSparkSessionExtension
  #     - SPARK_SQL_CATALOG=spark_catalog
  #     - SPARK_SQL_CATALOG_SPARK_CATALOG=org.apache.spark.sql.delta.catalog.DeltaCatalog
  #     - SPARK_HIVE_METASTORE_URIS=thrift://hive-metastore:9083
  #   volumes:
  #     - .:/app
  #     - ./conf/log4j2.properties:/opt/bitnami/spark/conf/log4j2.properties
  #   # networks:
  #   #   - spark-network

  # -----------------------------
  # Postgres (for DW + Airflow metastore)
  # -----------------------------
  postgres:
    image: postgres:15
    container_name: ${PROJECT_NAME}-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_DB_USER}
      POSTGRES_PASSWORD: ${POSTGRES_DB_PASSWORD}
      POSTGRES_DB: postgres
    ports:
      - "15432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_DB_USER} -d ${POSTGRES_DB_NAME:-postgres}"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    networks:
      - default
      - spark-network

  redis:
    # Redis is limited to 7.2-bookworm due to licencing change
    # https://redis.io/blog/redis-adopts-dual-source-available-licensing/
    image: redis:7.2-bookworm
    expose:
      - 6379
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 30s
      retries: 50
      start_period: 30s
    restart: always
    networks:
      - default
      - spark-network

  alembic-run:
    build:
      context: .
      dockerfile: create_dbs.Dockerfile # just bc it has alembic
    container_name: ${PROJECT_NAME}-alembic-run
    volumes:
      - .:/app
    working_dir: /app
    environment:
      POSTGRES_DB_HOST: postgres
      POSTGRES_DB_NAME: ${POSTGRES_DB_NAME}
      POSTGRES_DB_USER: ${POSTGRES_DB_USER}
      POSTGRES_DB_PASSWORD: ${POSTGRES_DB_PASSWORD}
    networks:
      - default
      - spark-network
    profiles:
      - tools
    

    depends_on:
      create-dbs:
        condition: service_completed_successfully
    
    command: ["alembic", "upgrade", "head"]

  create-dbs:
    env_file:
    - .env
    build:
      context: .
      dockerfile: create_dbs.Dockerfile
    depends_on:
      postgres:
        condition: service_healthy
    networks:      # <--- Add this just to be safe and explicit
      - default

  airflow-apiserver:
    <<: *airflow-common
    container_name: ${PROJECT_NAME}-airflow-apiserver
    command: api-server
    ports:
      - "8081:8080"
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://localhost:8080/api/v2/version"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s
    restart: always
    depends_on:
      postgres:
        condition: service_healthy
      airflow-init:
        condition: service_completed_successfully

  airflow-scheduler:
    <<: *airflow-common
    container_name: ${PROJECT_NAME}-airflow-scheduler
    command: scheduler
    restart: always
    depends_on:
      postgres:
        condition: service_healthy
      airflow-init:
        condition: service_completed_successfully

  airflow-dag-processor:
    container_name: ${PROJECT_NAME}-airflow-dag-processor
    <<: *airflow-common
    command: dag-processor
    restart: always
    depends_on:
      postgres:
        condition: service_healthy
      airflow-init:
        condition: service_completed_successfully

  airflow-init:
    container_name: ${PROJECT_NAME}-airflow-init
    <<: *airflow-common
    environment:
      <<: *airflow-common-env
      _AIRFLOW_DB_MIGRATE: 'true'
      _AIRFLOW_WWW_USER_CREATE: 'true'
      _AIRFLOW_WWW_USER_USERNAME: ${_AIRFLOW_WWW_USER_USERNAME:-airflow}
      _AIRFLOW_WWW_USER_PASSWORD: ${_AIRFLOW_WWW_USER_PASSWORD:-airflow}
      _PIP_ADDITIONAL_REQUIREMENTS: ''
    user: "1000:0"
    command: >
      bash -c "
        airflow db migrate
      "

  airflow-cli:
    container_name: ${PROJECT_NAME}-airflow-cli
    <<: *airflow-common
    command: bash -c "airflow"
    depends_on:
      postgres:
        condition: service_healthy


  airflow-worker:
    <<: *airflow-common
    command: celery worker
    healthcheck:
      # yamllint disable rule:line-length
      test:
        - "CMD-SHELL"
        - 'celery --app airflow.providers.celery.executors.celery_executor.app inspect ping -d "celery@$${HOSTNAME}" || celery --app airflow.executors.celery_executor.app inspect ping -d "celery@$${HOSTNAME}"'
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s
    environment:
      <<: *airflow-common-env
      # Required to handle warm shutdown of the celery workers properly
      # See https://airflow.apache.org/docs/docker-stack/entrypoint.html#signal-propagation
      DUMB_INIT_SETSID: "0"
    restart: always
    depends_on:
      <<: *airflow-common-depends-on
      airflow-apiserver:
        condition: service_healthy
      airflow-init:
        condition: service_completed_successfully

  airflow-triggerer:
    <<: *airflow-common
    command: triggerer
    healthcheck:
      test: ["CMD-SHELL", 'airflow jobs check --job-type TriggererJob --hostname "$${HOSTNAME}"']
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s
    restart: always
    depends_on:
      <<: *airflow-common-depends-on
      airflow-init:
        condition: service_completed_successfully


  # You can enable flower by adding "--profile flower" option e.g. docker-compose --profile flower up
  # or by explicitly targeted on the command line e.g. docker-compose up flower.
  # See: https://docs.docker.com/compose/profiles/
  flower:
    <<: *airflow-common
    command: celery flower
    profiles:
      - flower
    ports:
      - "5555:5555"
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://localhost:5555/"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s
    restart: always
    depends_on:
      <<: *airflow-common-depends-on
      airflow-init:
        condition: service_completed_successfully

volumes:
  shared-jars:
  postgres-data:
  spark-warehouse:

networks:
  spark-network:
    external: true